import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import security from 'eslint-plugin-security'

export default tseslint.config(
  { ignores: [
    // Build outputs
    'dist/**',
    '.next/**',
    'node_modules/**',
    'coverage/**',
    '.swc/**',
    'storybook-static/**',
    'build/**',
    'out/**',
    // Config / infra / docs
    'drizzle/**',
    'terraform/**',
    'docker/**',
    'helm/**',
    'k8s/**',
    'monitoring/**',
    'public/**',
    'docs/**',
    // AI / IDE / tool folders
    '.agent/**',
    '.agents/**',
    '.claude/**',
    '.kiro/**',
    '.trae/**',
    '.qwen/**',
    '.qodo/**',
    '.security/**',
    '.security-backups/**',
    '.husky/**',
    '.github/**',
    '.vercel/**',
    '.vscode/**',
    '.storybook/**',
    // Project extras outside src
    'api/**',
    'e2e/**',
    'tests/**',
    'scripts/**',
    'src/scripts/**',
    '__mocks__/**',
    'empty_dir/**',
    'sdk/**',
    'requests/**',
    // Config files at root
    '*.config.*',
    '*.config-*.*',
    '*.config*',
    '*.rc.*',
    '*.rc',
    '.lintstagedrc.js',
    'playwright.config.ts',
    'vitest.config.ts',
    'next.config.js',
    'tailwind.config.js',
    'postcss.config.js',
    'security.config.js',
    'drizzle.config.ts',
    'eslint.config.js',
    // Misc
    'vitest.config.ts.timestamp-*',
    '*.backup-*',
    '*.log',
    'CHANGELOG.md',
    'README.md',
    'CLAUDE.md',
    'CONTRIBUTING.md'
  ] },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ['**/*.{ts,tsx,js,jsx}'],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
      'security': security,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      'react-refresh/only-export-components': 'off',
      'react-hooks/rules-of-hooks': 'warn',
      // Security rules — CRITICAL ONLY, never ignored
      'security/detect-object-injection': 'warn',
      'security/detect-unsafe-regex': 'warn',
      'security/detect-eval-with-expression': 'error',
      'security/detect-no-csrf-before-method-override': 'error',
      'security/detect-child-process': 'error',
      'security/detect-disable-mustache-escape': 'error',
      // Best practices — only truly dangerous patterns block builds
      'no-debugger': 'error',
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-new-func': 'error',
      // Noise-reduction: accumulated debt from 5+ AAs — monitor, don't block
      'no-console': 'off',
      'no-empty': 'off',
      'no-constant-binary-expression': 'warn',
      'security/detect-non-literal-regexp': 'warn',
      'security/detect-buffer-noassert': 'warn',
      'security/detect-non-literal-fs-filename': 'off',
      'security/detect-non-literal-require': 'off',
      'security/detect-possible-timing-attacks': 'warn',
      'security/detect-pseudoRandomBytes': 'warn',
      'security/detect-new-buffer': 'warn',
      '@typescript-eslint/no-unused-vars': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-require-imports': 'off',
      '@typescript-eslint/no-empty-object-type': 'off',
      '@typescript-eslint/ban-ts-comment': 'off',
      '@typescript-eslint/no-misused-new': 'off',
      'no-useless-escape': 'off',
      'no-case-declarations': 'off',
      'no-control-regex': 'off',
      'prefer-const': 'off',
      '@typescript-eslint/ban-types': 'off',
      '@typescript-eslint/no-unsafe-function-type': 'off',
    },
  },
)
