/**
 * 📅 MOCK DATA: Vencimientos - Datos Reales Canal 13 (RDF Media)
 * 
 * @description Datos de prueba para desarrollo local sin base de datos.
 *              Información real de las emisoras del grupo Canal 13 (Chile).
 * 
 * @version 1.0.0
 */

// ═══════════════════════════════════════════════════════════════
// IDs FIJOS PARA CONSISTENCIA
// ═══════════════════════════════════════════════════════════════

export const TENANT_ID = '00000000-0000-0000-0000-000000000001'
export const USER_ID = '00000000-0000-0000-0000-000000000001'

// Emisoras
export const EMI_PLAY = '11111111-1111-1111-1111-111111111111'
export const EMI_SONAR = '22222222-2222-2222-2222-222222222222'
export const EMI_T13 = '33333333-3333-3333-3333-333333333333'
export const EMI_13C = '44444444-4444-4444-4444-444444444444'

// ═══════════════════════════════════════════════════════════════
// EMISORAS REALES CANAL 13
// ═══════════════════════════════════════════════════════════════

export const emisorasMock = [
    {
        id: EMI_PLAY,
        nombre: 'Play FM',
        nombreComercial: 'Play FM 100.9',
        frecuencia: '100.9',
        tipo: 'FM',
        slogan: 'La radio que escucha Chile',
        programasCount: 8,
        estado: 'activa' as const,
    },
    {
        id: EMI_SONAR,
        nombre: 'Sonar FM',
        nombreComercial: 'Sonar FM 105.3',
        frecuencia: '105.3',
        tipo: 'FM',
        slogan: 'Rock desde el corazón',
        programasCount: 9,
        estado: 'activa' as const,
    },
    {
        id: EMI_T13,
        nombre: 'Tele13 Radio',
        nombreComercial: 'Tele13 Radio 103.3',
        frecuencia: '103.3',
        tipo: 'FM',
        slogan: 'Información que importa',
        programasCount: 10,
        estado: 'activa' as const,
    },
    {
        id: EMI_13C,
        nombre: 'Radio 13C',
        nombreComercial: 'Radio 13C',
        frecuencia: 'Digital',
        tipo: 'Online',
        slogan: 'Cooltura en el aire',
        programasCount: 7,
        estado: 'activa' as const,
    },
]

// ═══════════════════════════════════════════════════════════════
// PROGRAMAS REALES
// ═══════════════════════════════════════════════════════════════

export const programasMock = [
    // PLAY FM
    {
        id: 'p1111111-1111-1111-1111-111111111112',
        codigo: 'PLAY-AGENDA',
        emiId: EMI_PLAY,
        emiNombre: 'Play FM 100.9',
        nombre: 'Agenda Play',
        descripcion: 'Mañana informativa y musical con Cata Chuaqui. Noticias, entrevistas y la mejor música para comenzar el día.',
        horario: { horaInicio: '07:00', horaFin: '09:00', diasSemana: [1, 2, 3, 4, 5] },
        conductorPrincipal: 'Cata Chuaqui',
        cupos: {
            tipoA: { total: 20, ocupados: 12, disponibles: 8 },
            tipoB: { total: 24, ocupados: 10, disponibles: 14 },
            menciones: { total: 8, ocupados: 5, disponibles: 3 },
        },
        estado: 'ACTIVO',
        esPrime: true,
        tieneCuposDisponibles: true,
        revenueActual: 21000000,
        revenuePotencial: 45000000,
        listaEsperaCount: 4,
        disponibilidad: { totalCupos: 52, totalOcupados: 27, totalDisponibles: 25, ocupacionPorcentaje: 52 },
    },
    {
        id: 'p1111111-1111-1111-1111-111111111113',
        codigo: 'PLAY-LOOK',
        emiId: EMI_PLAY,
        emiNombre: 'Play FM 100.9',
        nombre: 'Look',
        descripcion: 'Moda, tendencias y estilo de vida con Milla Kemp. Lo último en cultura pop y entretenimiento.',
        horario: { horaInicio: '09:00', horaFin: '11:00', diasSemana: [1, 2, 3, 4, 5] },
        conductorPrincipal: 'Milla Kemp',
        cupos: {
            tipoA: { total: 8, ocupados: 5, disponibles: 3 },
            tipoB: { total: 16, ocupados: 8, disponibles: 8 },
            menciones: { total: 6, ocupados: 3, disponibles: 3 },
        },
        estado: 'ACTIVO',
        esPrime: false,
        tieneCuposDisponibles: true,
        revenueActual: 15000000,
        revenuePotencial: 32000000,
        listaEsperaCount: 2,
        disponibilidad: { totalCupos: 30, totalOcupados: 16, totalDisponibles: 14, ocupacionPorcentaje: 53 },
    },
    {
        id: 'p1111111-1111-1111-1111-111111111114',
        codigo: 'PLAY-LIST',
        emiId: EMI_PLAY,
        emiNombre: 'Play FM 100.9',
        nombre: 'Playlist',
        descripcion: 'Las playlists más escuchadas del momento. Música sin interrupciones para tu día con Rosario Grez.',
        horario: { horaInicio: '10:00', horaFin: '13:00', diasSemana: [1, 2, 3, 4, 5] },
        conductorPrincipal: 'Rosario Grez',
        cupos: {
            tipoA: { total: 20, ocupados: 10, disponibles: 10 },
            tipoB: { total: 20, ocupados: 9, disponibles: 11 },
            menciones: { total: 8, ocupados: 4, disponibles: 4 },
        },
        estado: 'ACTIVO',
        esPrime: true,
        tieneCuposDisponibles: true,
        revenueActual: 18000000,
        revenuePotencial: 38000000,
        listaEsperaCount: 3,
        disponibilidad: { totalCupos: 48, totalOcupados: 23, totalDisponibles: 25, ocupacionPorcentaje: 48 },
    },
    {
        id: 'p1111111-1111-1111-1111-111111111115',
        codigo: 'PLAY-POWER',
        emiId: EMI_PLAY,
        emiNombre: 'Play FM 100.9',
        nombre: 'Play Power',
        descripcion: 'La tarde con energía. Música, conversación y actualidad con Vero Calabi.',
        horario: { horaInicio: '13:00', horaFin: '16:00', diasSemana: [1, 2, 3, 4, 5] },
        conductorPrincipal: 'Vero Calabi',
        cupos: {
            tipoA: { total: 17, ocupados: 11, disponibles: 6 },
            tipoB: { total: 22, ocupados: 12, disponibles: 10 },
            menciones: { total: 8, ocupados: 5, disponibles: 3 },
        },
        estado: 'ACTIVO',
        esPrime: true,
        tieneCuposDisponibles: true,
        revenueActual: 22000000,
        revenuePotencial: 48000000,
        listaEsperaCount: 3,
        disponibilidad: { totalCupos: 47, totalOcupados: 28, totalDisponibles: 19, ocupacionPorcentaje: 60 },
    },
    {
        id: 'p1111111-1111-1111-1111-111111111116',
        codigo: 'PLAY-FUERA',
        emiId: EMI_PLAY,
        emiNombre: 'Play FM 100.9',
        nombre: 'Fuera de Contexto',
        descripcion: 'Conversaciones impertinentes con Milla Kemp. Actualidad, cultura pop y entrevistas sin filtros.',
        horario: { horaInicio: '16:00', horaFin: '19:00', diasSemana: [1, 2, 3, 4, 5] },
        conductorPrincipal: 'Milla Kemp',
        cupos: {
            tipoA: { total: 10, ocupados: 6, disponibles: 4 },
            tipoB: { total: 18, ocupados: 9, disponibles: 9 },
            menciones: { total: 5, ocupados: 2, disponibles: 3 },
        },
        estado: 'ACTIVO',
        esPrime: false,
        tieneCuposDisponibles: true,
        revenueActual: 16000000,
        revenuePotencial: 35000000,
        listaEsperaCount: 2,
        disponibilidad: { totalCupos: 33, totalOcupados: 17, totalDisponibles: 16, ocupacionPorcentaje: 52 },
    },
    {
        id: 'p1111111-1111-1111-1111-111111111117',
        codigo: 'PLAY-GEN',
        emiId: EMI_PLAY,
        emiNombre: 'Play FM 100.9',
        nombre: 'Generación Play',
        descripcion: 'La generación que creció con la mejor música. Nostalgia y actualidad con Ignacio Franzani.',
        horario: { horaInicio: '19:00', horaFin: '22:00', diasSemana: [1, 2, 3, 4, 5] },
        conductorPrincipal: 'Ignacio Franzani',
        cupos: {
            tipoA: { total: 8, ocupados: 3, disponibles: 5 },
            tipoB: { total: 16, ocupados: 6, disponibles: 10 },
            menciones: { total: 4, ocupados: 1, disponibles: 3 },
        },
        estado: 'ACTIVO',
        esPrime: false,
        tieneCuposDisponibles: true,
        revenueActual: 11000000,
        revenuePotencial: 28000000,
        listaEsperaCount: 1,
        disponibilidad: { totalCupos: 28, totalOcupados: 10, totalDisponibles: 18, ocupacionPorcentaje: 36 },
    },

    // SONAR FM
    {
        id: 'p2222222-2222-2222-2222-222222222221',
        codigo: 'SONAR-INFO',
        emiId: EMI_SONAR,
        emiNombre: 'Sonar FM 105.3',
        nombre: 'Sonar Informativo',
        descripcion: 'Las noticias del rock y la actualidad chilena con Pablo Aranzaes. Información con actitud rock.',
        horario: { horaInicio: '07:00', horaFin: '09:00', diasSemana: [1, 2, 3, 4, 5] },
        conductorPrincipal: 'Pablo Aranzaes',
        cupos: {
            tipoA: { total: 22, ocupados: 15, disponibles: 7 },
            tipoB: { total: 18, ocupados: 10, disponibles: 8 },
            menciones: { total: 8, ocupados: 5, disponibles: 3 },
        },
        estado: 'ACTIVO',
        esPrime: true,
        tieneCuposDisponibles: true,
        revenueActual: 19500000,
        revenuePotencial: 42000000,
        listaEsperaCount: 3,
        disponibilidad: { totalCupos: 48, totalOcupados: 30, totalDisponibles: 18, ocupacionPorcentaje: 63 },
    },
    {
        id: 'p2222222-2222-2222-2222-222222222222',
        codigo: 'SONAR-RADIO',
        emiId: EMI_SONAR,
        emiNombre: 'Sonar FM 105.3',
        nombre: 'Radiotransmisor',
        descripcion: 'El viaje sonoro de Alfredo Lewin. Rock clásico y nuevas propuestas musicales.',
        horario: { horaInicio: '09:00', horaFin: '12:00', diasSemana: [1, 2, 3, 4, 5] },
        conductorPrincipal: 'Alfredo Lewin',
        cupos: {
            tipoA: { total: 12, ocupados: 8, disponibles: 4 },
            tipoB: { total: 16, ocupados: 9, disponibles: 7 },
            menciones: { total: 6, ocupados: 3, disponibles: 3 },
        },
        estado: 'ACTIVO',
        esPrime: true,
        tieneCuposDisponibles: true,
        revenueActual: 15000000,
        revenuePotencial: 35000000,
        listaEsperaCount: 2,
        disponibilidad: { totalCupos: 34, totalOcupados: 20, totalDisponibles: 14, ocupacionPorcentaje: 59 },
    },
    {
        id: 'p2222222-2222-2222-2222-222222222223',
        codigo: 'SONAR-ROCK',
        emiId: EMI_SONAR,
        emiNombre: 'Sonar FM 105.3',
        nombre: 'Rock y Guitarras',
        descripcion: 'El sonido de las seis cuerdas. De Hendrix a los guitarristas chilenos contemporáneos con Pablo Márquez.',
        horario: { horaInicio: '12:00', horaFin: '15:00', diasSemana: [1, 2, 3, 4, 5] },
        conductorPrincipal: 'Pablo Márquez',
        cupos: {
            tipoA: { total: 10, ocupados: 5, disponibles: 5 },
            tipoB: { total: 14, ocupados: 7, disponibles: 7 },
            menciones: { total: 5, ocupados: 2, disponibles: 3 },
        },
        estado: 'ACTIVO',
        esPrime: false,
        tieneCuposDisponibles: true,
        revenueActual: 12000000,
        revenuePotencial: 28000000,
        listaEsperaCount: 1,
        disponibilidad: { totalCupos: 29, totalOcupados: 14, totalDisponibles: 15, ocupacionPorcentaje: 48 },
    },
    {
        id: 'p2222222-2222-2222-2222-222222222224',
        codigo: 'SONAR-CLAS',
        emiId: EMI_SONAR,
        emiNombre: 'Sonar FM 105.3',
        nombre: 'Sonar Clásico',
        descripcion: 'Los clásicos del rock en su versión más pura. Con Francisco Reinoso.',
        horario: { horaInicio: '15:00', horaFin: '18:00', diasSemana: [1, 2, 3, 4, 5] },
        conductorPrincipal: 'Francisco Reinoso',
        cupos: {
            tipoA: { total: 9, ocupados: 5, disponibles: 4 },
            tipoB: { total: 14, ocupados: 7, disponibles: 7 },
            menciones: { total: 5, ocupados: 2, disponibles: 3 },
        },
        estado: 'ACTIVO',
        esPrime: false,
        tieneCuposDisponibles: true,
        revenueActual: 11000000,
        revenuePotencial: 26000000,
        listaEsperaCount: 1,
        disponibilidad: { totalCupos: 28, totalOcupados: 14, totalDisponibles: 14, ocupacionPorcentaje: 50 },
    },
    {
        id: 'p2222222-2222-2222-2222-222222222225',
        codigo: 'SONAR-HERO',
        emiId: EMI_SONAR,
        emiNombre: 'Sonar FM 105.3',
        nombre: 'Sonar Héroes',
        descripcion: 'Homenaje a las leyendas del rock. Historias, anécdotas y los himnos de siempre.',
        horario: { horaInicio: '18:00', horaFin: '21:00', diasSemana: [1, 2, 3, 4, 5] },
        conductorPrincipal: 'Ignacio Pérez Tuesta',
        cupos: {
            tipoA: { total: 16, ocupados: 10, disponibles: 6 },
            tipoB: { total: 18, ocupados: 10, disponibles: 8 },
            menciones: { total: 6, ocupados: 3, disponibles: 3 },
        },
        estado: 'ACTIVO',
        esPrime: true,
        tieneCuposDisponibles: true,
        revenueActual: 10000000,
        revenuePotencial: 24000000,
        listaEsperaCount: 2,
        disponibilidad: { totalCupos: 40, totalOcupados: 23, totalDisponibles: 17, ocupacionPorcentaje: 58 },
    },
    {
        id: 'p2222222-2222-2222-2222-222222222226',
        codigo: 'SONAR-DEP',
        emiId: EMI_SONAR,
        emiNombre: 'Sonar FM 105.3',
        nombre: 'Sonar Deportivo',
        descripcion: 'El deporte con la actitud del rock. Análisis, entrevistas y pasión con Pablo Aranzaes.',
        horario: { horaInicio: '21:00', horaFin: '23:00', diasSemana: [1, 2, 3, 4, 5] },
        conductorPrincipal: 'Pablo Aranzaes',
        cupos: {
            tipoA: { total: 2, ocupados: 1, disponibles: 1 },
            tipoB: { total: 8, ocupados: 4, disponibles: 4 },
            menciones: { total: 3, ocupados: 1, disponibles: 2 },
        },
        estado: 'ACTIVO',
        esPrime: false,
        tieneCuposDisponibles: true,
        revenueActual: 6500000,
        revenuePotencial: 18000000,
        listaEsperaCount: 0,
        disponibilidad: { totalCupos: 13, totalOcupados: 6, totalDisponibles: 7, ocupacionPorcentaje: 46 },
    },

    // TELE13 RADIO
    {
        id: 'p3333333-3333-3333-3333-333333333331',
        codigo: 'T13-MESA',
        emiId: EMI_T13,
        emiNombre: 'Tele13 Radio 103.3',
        nombre: 'Mesa Central',
        descripcion: 'El noticiero matinal de referencia en Chile. Análisis profundo de la actualidad con Iván Valenzuela.',
        horario: { horaInicio: '07:00', horaFin: '10:00', diasSemana: [1, 2, 3, 4, 5] },
        conductorPrincipal: 'Iván Valenzuela',
        cupos: {
            tipoA: { total: 25, ocupados: 18, disponibles: 7 },
            tipoB: { total: 30, ocupados: 20, disponibles: 10 },
            menciones: { total: 12, ocupados: 8, disponibles: 4 },
        },
        estado: 'ACTIVO',
        esPrime: true,
        tieneCuposDisponibles: true,
        revenueActual: 52000000,
        revenuePotencial: 95000000,
        listaEsperaCount: 5,
        disponibilidad: { totalCupos: 67, totalOcupados: 46, totalDisponibles: 21, ocupacionPorcentaje: 69 },
    },
    {
        id: 'p3333333-3333-3333-3333-333333333332',
        codigo: 'T13-MANANA',
        emiId: EMI_T13,
        emiNombre: 'Tele13 Radio 103.3',
        nombre: 'Lo que marca la mañana',
        descripcion: 'Actualidad, entrevistas y el análisis que marca la jornada informativa con Andrea Rivera.',
        horario: { horaInicio: '10:00', horaFin: '12:00', diasSemana: [1, 2, 3, 4, 5] },
        conductorPrincipal: 'Andrea Rivera',
        cupos: {
            tipoA: { total: 5, ocupados: 3, disponibles: 2 },
            tipoB: { total: 12, ocupados: 6, disponibles: 6 },
            menciones: { total: 4, ocupados: 2, disponibles: 2 },
        },
        estado: 'ACTIVO',
        esPrime: false,
        tieneCuposDisponibles: true,
        revenueActual: 12000000,
        revenuePotencial: 28000000,
        listaEsperaCount: 1,
        disponibilidad: { totalCupos: 21, totalOcupados: 11, totalDisponibles: 10, ocupacionPorcentaje: 52 },
    },
    {
        id: 'p3333333-3333-3333-3333-333333333333',
        codigo: 'T13-CLICK',
        emiId: EMI_T13,
        emiNombre: 'Tele13 Radio 103.3',
        nombre: 'Doble Click',
        descripcion: 'Tecnología, innovación y cultura digital con Ramón Ulloa. El futuro en un click.',
        horario: { horaInicio: '17:00', horaFin: '19:00', diasSemana: [1, 2, 3, 4, 5] },
        conductorPrincipal: 'Ramón Ulloa',
        cupos: {
            tipoA: { total: 12, ocupados: 8, disponibles: 4 },
            tipoB: { total: 16, ocupados: 9, disponibles: 7 },
            menciones: { total: 6, ocupados: 3, disponibles: 3 },
        },
        estado: 'ACTIVO',
        esPrime: true,
        tieneCuposDisponibles: true,
        revenueActual: 16000000,
        revenuePotencial: 35000000,
        listaEsperaCount: 2,
        disponibilidad: { totalCupos: 34, totalOcupados: 20, totalDisponibles: 14, ocupacionPorcentaje: 59 },
    },
    {
        id: 'p3333333-3333-3333-3333-333333333337',
        codigo: 'T13-CONEX',
        emiId: EMI_T13,
        emiNombre: 'Tele13 Radio 103.3',
        nombre: 'Conexión Tele13',
        descripcion: 'La conexión directa con la actualidad nacional e internacional. Edición nocturna informativa.',
        horario: { horaInicio: '19:00', horaFin: '20:00', diasSemana: [1, 2, 3, 4, 5] },
        conductorPrincipal: 'Ramón Ulloa',
        cupos: {
            tipoA: { total: 14, ocupados: 10, disponibles: 4 },
            tipoB: { total: 18, ocupados: 12, disponibles: 6 },
            menciones: { total: 8, ocupados: 5, disponibles: 3 },
        },
        estado: 'ACTIVO',
        esPrime: true,
        tieneCuposDisponibles: true,
        revenueActual: 28000000,
        revenuePotencial: 58000000,
        listaEsperaCount: 3,
        disponibilidad: { totalCupos: 40, totalOcupados: 27, totalDisponibles: 13, ocupacionPorcentaje: 68 },
    },
    {
        id: 'p3333333-3333-3333-3333-333333333338',
        codigo: 'T13-PAGINA',
        emiId: EMI_T13,
        emiNombre: 'Tele13 Radio 103.3',
        nombre: 'Página 13',
        descripcion: 'El análisis político de fondo. Las historias detrás de las noticias con Kike Mujica y Consuelo Saavedra.',
        horario: { horaInicio: '20:00', horaFin: '21:00', diasSemana: [1, 2, 3, 4, 5] },
        conductorPrincipal: 'Kike Mujica',
        cupos: {
            tipoA: { total: 14, ocupados: 9, disponibles: 5 },
            tipoB: { total: 18, ocupados: 10, disponibles: 8 },
            menciones: { total: 8, ocupados: 4, disponibles: 4 },
        },
        estado: 'ACTIVO',
        esPrime: true,
        tieneCuposDisponibles: true,
        revenueActual: 25000000,
        revenuePotencial: 52000000,
        listaEsperaCount: 3,
        disponibilidad: { totalCupos: 40, totalOcupados: 23, totalDisponibles: 17, ocupacionPorcentaje: 58 },
    },

    // RADIO 13C
    {
        id: 'p4444444-4444-4444-4444-444444444441',
        codigo: '13C-CUATRO',
        emiId: EMI_13C,
        emiNombre: 'Radio 13C',
        nombre: 'Cuatro Cabezas',
        descripcion: 'Cultura, humor y conversación con Kike Mujica. Cuatro cabezas piensan mejor que una.',
        horario: { horaInicio: '07:00', horaFin: '09:00', diasSemana: [1, 2, 3, 4, 5] },
        conductorPrincipal: 'Kike Mujica',
        cupos: {
            tipoA: { total: 13, ocupados: 8, disponibles: 5 },
            tipoB: { total: 10, ocupados: 5, disponibles: 5 },
            menciones: { total: 6, ocupados: 3, disponibles: 3 },
        },
        estado: 'ACTIVO',
        esPrime: false,
        tieneCuposDisponibles: true,
        revenueActual: 18000000,
        revenuePotencial: 35000000,
        listaEsperaCount: 2,
        disponibilidad: { totalCupos: 29, totalOcupados: 16, totalDisponibles: 13, ocupacionPorcentaje: 55 },
    },
    {
        id: 'p4444444-4444-4444-4444-444444444444',
        codigo: '13C-DESPUES',
        emiId: EMI_13C,
        emiNombre: 'Radio 13C',
        nombre: 'Después de Todo',
        descripcion: 'Reflexiones, entrevistas y conversaciones profundas con Soledad Onetto.',
        horario: { horaInicio: '10:00', horaFin: '12:00', diasSemana: [1, 2, 3, 4, 5] },
        conductorPrincipal: 'Soledad Onetto',
        cupos: {
            tipoA: { total: 12, ocupados: 7, disponibles: 5 },
            tipoB: { total: 10, ocupados: 5, disponibles: 5 },
            menciones: { total: 6, ocupados: 3, disponibles: 3 },
        },
        estado: 'ACTIVO',
        esPrime: false,
        tieneCuposDisponibles: true,
        revenueActual: 17000000,
        revenuePotencial: 36000000,
        listaEsperaCount: 2,
        disponibilidad: { totalCupos: 28, totalOcupados: 15, totalDisponibles: 13, ocupacionPorcentaje: 54 },
    },
    {
        id: 'p4444444-4444-4444-4444-444444444445',
        codigo: '13C-CORR',
        emiId: EMI_13C,
        emiNombre: 'Radio 13C',
        nombre: 'Corresponsales',
        descripcion: 'Noticias desde las regiones con Marcelo Comparini. La actualidad local de todo Chile.',
        horario: { horaInicio: '12:00', horaFin: '13:00', diasSemana: [1, 2, 3, 4, 5] },
        conductorPrincipal: 'Marcelo Comparini',
        cupos: {
            tipoA: { total: 12, ocupados: 7, disponibles: 5 },
            tipoB: { total: 10, ocupados: 5, disponibles: 5 },
            menciones: { total: 5, ocupados: 2, disponibles: 3 },
        },
        estado: 'ACTIVO',
        esPrime: false,
        tieneCuposDisponibles: true,
        revenueActual: 14000000,
        revenuePotencial: 30000000,
        listaEsperaCount: 1,
        disponibilidad: { totalCupos: 27, totalOcupados: 14, totalDisponibles: 13, ocupacionPorcentaje: 52 },
    },
]

// ═══════════════════════════════════════════════════════════════
// VENCIMIENTOS MOCK
// ═══════════════════════════════════════════════════════════════

const hoy = new Date()

function getFechaVencimiento(dias: number): string {
    const fecha = new Date(hoy)
    fecha.setDate(fecha.getDate() + dias)
    return fecha.toISOString().split('T')[0]
}

export const vencimientosMock = [
    {
        id: 'vto-001',
        programaId: 'p3333333-3333-3333-3333-333333333331',
        programaNombre: 'Mesa Central',
        emiId: EMI_T13,
        emiNombre: 'Tele13 Radio 103.3',
        clienteId: 'cli-001',
        clienteNombre: 'Coca-Cola Chile',
        clienteRubro: 'Bebidas',
        ejecutivoId: 'usr-001',
        ejecutivoNombre: 'Pedro Sánchez',
        tipoAuspicio: 'Auspicio Completo',
        fechaFin: getFechaVencimiento(3),
        diasRestantes: 3,
        nivelAlerta: 'rojo',
        accionSugerida: 'Contactar cliente para renovación',
        valor: 17500000,
        estado: 'ACTIVO',
    },
    {
        id: 'vto-002',
        programaId: 'p1111111-1111-1111-1111-111111111115',
        programaNombre: 'Play Power',
        emiId: EMI_PLAY,
        emiNombre: 'Play FM 100.9',
        clienteId: 'cli-002',
        clienteNombre: 'Bimbo Chile',
        clienteRubro: 'Alimentos',
        ejecutivoId: 'usr-002',
        ejecutivoNombre: 'María López',
        tipoAuspicio: 'Auspicio Parcial',
        fechaFin: getFechaVencimiento(7),
        diasRestantes: 7,
        nivelAlerta: 'amarillo',
        accionSugerida: 'Preparar propuesta de renovación',
        valor: 8500000,
        estado: 'ACTIVO',
    },
    {
        id: 'vto-003',
        programaId: 'p2222222-2222-2222-2222-222222222221',
        programaNombre: 'Sonar Informativo',
        emiId: EMI_SONAR,
        emiNombre: 'Sonar FM 105.3',
        clienteId: 'cli-003',
        clienteNombre: 'Samsung Chile',
        clienteRubro: 'Tecnología',
        ejecutivoId: 'usr-003',
        ejecutivoNombre: 'Juan Pérez',
        tipoAuspicio: 'Auspicio Premium',
        fechaFin: getFechaVencimiento(12),
        diasRestantes: 12,
        nivelAlerta: 'amarillo',
        accionSugerida: 'Revisión de contrato',
        valor: 12000000,
        estado: 'ACTIVO',
    },
    {
        id: 'vto-004',
        programaId: 'p3333333-3333-3333-3333-333333333333',
        programaNombre: 'Doble Click',
        emiId: EMI_T13,
        emiNombre: 'Tele13 Radio 103.3',
        clienteId: 'cli-004',
        clienteNombre: 'Entel',
        clienteRubro: 'Telecomunicaciones',
        ejecutivoId: 'usr-004',
        ejecutivoNombre: 'Ana Gómez',
        tipoAuspicio: 'Auspicio de Segmento',
        fechaFin: getFechaVencimiento(18),
        diasRestantes: 18,
        nivelAlerta: 'verde',
        accionSugerida: 'OK - Seguimiento normal',
        valor: 7000000,
        estado: 'ACTIVO',
    },
    {
        id: 'vto-005',
        programaId: 'p1111111-1111-1111-1111-111111111112',
        programaNombre: 'Agenda Play',
        emiId: EMI_PLAY,
        emiNombre: 'Play FM 100.9',
        clienteId: 'cli-005',
        clienteNombre: 'Falabella',
        clienteRubro: 'Retail',
        ejecutivoId: 'usr-001',
        ejecutivoNombre: 'Pedro Sánchez',
        tipoAuspicio: 'Auspicio Completo',
        fechaFin: getFechaVencimiento(25),
        diasRestantes: 25,
        nivelAlerta: 'verde',
        accionSugerida: 'OK - En monitoreo',
        valor: 22000000,
        estado: 'ACTIVO',
    },
    {
        id: 'vto-006',
        programaId: 'p4444444-4444-4444-4444-444444444441',
        programaNombre: 'Cuatro Cabezas',
        emiId: EMI_13C,
        emiNombre: 'Radio 13C',
        clienteId: 'cli-006',
        clienteNombre: 'Banco de Chile',
        clienteRubro: 'Banca',
        ejecutivoId: 'usr-005',
        ejecutivoNombre: 'Carlos Ruiz',
        tipoAuspicio: 'Auspicio Digital',
        fechaFin: getFechaVencimiento(1),
        diasRestantes: 1,
        nivelAlerta: 'critico',
        accionSugerida: 'URGENTE - Renovación inmediata',
        valor: 9500000,
        estado: 'ACTIVO',
    },
]

// ═══════════════════════════════════════════════════════════════
// ALERTAS MOCK
// ═══════════════════════════════════════════════════════════════

export const alertasMock = [
    {
        id: 'alerta-001',
        tipo: 'vencimiento_proximo',
        prioridad: 'alta',
        titulo: 'Vencimiento crítico en 1 día',
        mensaje: 'El contrato de Banco de Chile en Cuatro Cabezas vence mañana. Se requiere renovación urgente.',
        programaId: 'p4444444-4444-4444-4444-444444444441',
        programaNombre: 'Cuatro Cabezas',
        emiNombre: 'Radio 13C',
        clienteNombre: 'Banco de Chile',
        diasRestantes: 1,
        leida: false,
        createdAt: new Date().toISOString(),
    },
    {
        id: 'alerta-002',
        tipo: 'ocupacion_alta',
        prioridad: 'media',
        titulo: 'Ocupación sobre 90% en Mesa Central',
        mensaje: 'El programa Mesa Central tiene una ocupación del 94%. Considerar aumentar tarifas.',
        programaId: 'p3333333-3333-3333-3333-333333333331',
        programaNombre: 'Mesa Central',
        emiNombre: 'Tele13 Radio 103.3',
        clienteNombre: undefined,
        diasRestantes: undefined,
        leida: false,
        createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'alerta-003',
        tipo: 'lista_espera',
        prioridad: 'baja',
        titulo: 'Nuevo cliente en lista de espera',
        mensaje: 'Cerro Chile ha solicitado inclusión en lista de espera para Agenda Play.',
        programaId: 'p1111111-1111-1111-1111-111111111112',
        programaNombre: 'Agenda Play',
        emiNombre: 'Play FM 100.9',
        clienteNombre: 'Cerro Chile',
        diasRestantes: undefined,
        leida: true,
        createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'alerta-004',
        tipo: 'renovacion_exitosa',
        prioridad: 'baja',
        titulo: 'Renovación completada',
        mensaje: 'El contrato de Coca-Cola Chile en Mesa Central ha sido renovado exitosamente.',
        programaId: 'p3333333-3333-3333-3333-333333333331',
        programaNombre: 'Mesa Central',
        emiNombre: 'Tele13 Radio 103.3',
        clienteNombre: 'Coca-Cola Chile',
        diasRestantes: undefined,
        leida: true,
        createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    },
]

// ═══════════════════════════════════════════════════════════════
// MÉTRICAS MOCK
// ═══════════════════════════════════════════════════════════════

export const metricasMock = {
    totalProgramas: programasMock.length,
    programasActivos: programasMock.filter(p => p.estado === 'ACTIVO').length,
    totalCuposDisponibles: programasMock.reduce((acc, p) => acc + p.disponibilidad.totalDisponibles, 0),
    ocupacionPromedio: Math.round(
        programasMock.reduce((acc, p) => acc + p.disponibilidad.ocupacionPorcentaje, 0) / programasMock.length
    ),
}

// ═══════════════════════════════════════════════════════════════
// CLIENTES POR PROGRAMA MOCK
// ═══════════════════════════════════════════════════════════════

export const clientesProgramaMock = [
    {
        id: 'cp-001',
        clienteId: 'cli-001',
        clienteNombre: 'Coca-Cola Chile',
        clienteRubro: 'Bebidas',
        tipoCupo: 'PREMIUM' as const,
        estado: 'ACTIVO' as const,
        fechaInicio: '2026-01-01',
        fechaFin: '2026-06-30',
        valor: 17500000,
        ejecutivoNombre: 'Pedro Sánchez',
    },
    {
        id: 'cp-002',
        clienteId: 'cli-002',
        clienteNombre: 'Bimbo Chile',
        clienteRubro: 'Alimentos',
        tipoCupo: 'STANDARD' as const,
        estado: 'ACTIVO' as const,
        fechaInicio: '2026-02-01',
        fechaFin: '2026-07-31',
        valor: 8500000,
        ejecutivoNombre: 'María López',
    },
    {
        id: 'cp-003',
        clienteId: 'cli-003',
        clienteNombre: 'Samsung Chile',
        clienteRubro: 'Tecnología',
        tipoCupo: 'PREMIUM' as const,
        estado: 'ACTIVO' as const,
        fechaInicio: '2026-01-15',
        fechaFin: '2026-06-15',
        valor: 12000000,
        ejecutivoNombre: 'Juan Pérez',
    },
    {
        id: 'cp-004',
        clienteId: 'cli-004',
        clienteNombre: 'Falabella',
        clienteRubro: 'Retail',
        tipoCupo: 'PREMIUM' as const,
        estado: 'POR_COMENZAR' as const,
        fechaInicio: '2026-05-01',
        fechaFin: '2026-10-31',
        valor: 22000000,
        ejecutivoNombre: 'Pedro Sánchez',
    },
    {
        id: 'cp-005',
        clienteId: 'cli-005',
        clienteNombre: 'Entel',
        clienteRubro: 'Telecomunicaciones',
        tipoCupo: 'STANDARD' as const,
        estado: 'ACTIVO' as const,
        fechaInicio: '2026-03-01',
        fechaFin: '2026-08-31',
        valor: 7000000,
        ejecutivoNombre: 'Ana Gómez',
    },
    {
        id: 'cp-006',
        clienteId: 'cli-006',
        clienteNombre: 'Banco de Chile',
        clienteRubro: 'Banca',
        tipoCupo: 'MENSAJE' as const,
        estado: 'LISTA_ESPERA' as const,
        fechaInicio: '2026-06-01',
        fechaFin: '2026-12-31',
        valor: 9500000,
        ejecutivoNombre: 'Carlos Ruiz',
    },
    {
        id: 'cp-007',
        clienteId: 'cli-007',
        clienteNombre: 'Movistar',
        clienteRubro: 'Telecomunicaciones',
        tipoCupo: 'STANDARD' as const,
        estado: 'LISTA_ESPERA' as const,
        fechaInicio: '2026-07-01',
        fechaFin: '2026-12-31',
        valor: 6000000,
        ejecutivoNombre: 'Luis Martín',
    },
]