'use client'

/**
 * 🎫 SILEXAR PULSE - Support Tickets ULTIMATE (Client)
 * Sistema de tickets profesional con Chat en Tiempo Real e IA
 * 
 * @description Support Ultimate:
 * - Chat en tiempo real con soporte
 * - Modo email/historial tradicional
 * - IA Assistant integrado
 * - Adjuntar archivos y capturas
 * - Captura automática de pantalla
 * - Número de ticket único
 * - Conteo de días transcurridos
 * - SLA y advertencias
 * - Cerrar/Reabrir tickets
 * - Auto-tickets por errores del sistema
 * 
 * @version 2025.3.0
 * @tier TIER_0_FORTUNE_10
 */

import { useState, useEffect, useRef, useCallback } from 'react'
import { 
  NeuromorphicCard, 
  NeuromorphicButton 
} from '@/components/ui/neuromorphic'
import {
  HelpCircle,
  Plus,
  MessageSquare,
  Clock,
  AlertCircle,
  Send,
  RefreshCw,
  Paperclip,
  Camera,
  X,
  AlertTriangle,
  Bug,
  Zap,
  CreditCard,
  Settings,
  Calendar,
  XCircle,
  RotateCcw,
  Cpu,
  Phone,
  MessageCircle,
  Bot,
  Sparkles,
  Wifi,
  WifiOff,
  Circle
} from 'lucide-react'

interface Attachment {
  id: string
  name: string
  type: 'image' | 'document' | 'screenshot'
  url: string
  size: string
  uploadedAt: Date
}

interface SystemInfo {
  browser: string
  os: string
  screenResolution: string
  url: string
  timestamp: Date
  userAgent: string
}

interface SupportTicket {
  id: string
  ticketNumber: string
  subject: string
  description: string
  category: 'bug' | 'error' | 'billing' | 'feature' | 'performance' | 'security' | 'general' | 'auto_error'
  priority: 'low' | 'medium' | 'high' | 'critical'
  status: 'open' | 'in_progress' | 'waiting_response' | 'resolved' | 'closed'
  createdAt: Date
  updatedAt: Date
  closedAt?: Date
  messages: TicketMessage[]
  attachments: Attachment[]
  systemInfo?: SystemInfo
  errorCode?: string
  errorStack?: string
  daysOpen: number
  slaDeadline: Date
  slaBreach: boolean
  assignedTo?: string
  // Chat features
  chatEnabled: boolean
  chatActive: boolean
  agentOnline?: boolean
  isAutoGenerated?: boolean
}

interface TicketMessage {
  id: string
  sender: 'client' | 'support' | 'ai' | 'system'
  senderName: string
  content: string
  timestamp: Date
  attachments?: Attachment[]
  isTyping?: boolean
}

interface FAQItem {
  id: string
  question: string
  answer: string
  category: string
  views: number
}

// Global error handler for auto-ticket generation
const setupAutoErrorHandler = (createAutoTicket: (error: ErrorEvent | PromiseRejectionEvent) => void) => {
  if (typeof window === 'undefined') return

  window.addEventListener('error', (event) => {
    createAutoTicket(event)
  })

  window.addEventListener('unhandledrejection', (event) => {
    createAutoTicket(event)
  })
}

export function SupportTickets() {
  const [tickets, setTickets] = useState<SupportTicket[]>([])
  const [faqs, setFaqs] = useState<FAQItem[]>([])
  const [selectedTicket, setSelectedTicket] = useState<SupportTicket | null>(null)
  const [isLoading, setIsLoading] = useState(true)
  const [showNewTicket, setShowNewTicket] = useState(false)
  const [newMessage, setNewMessage] = useState('')
  const [filter, setFilter] = useState<'all' | 'open' | 'resolved' | 'closed'>('all')
  const [pendingAttachments, setPendingAttachments] = useState<Attachment[]>([])
  const [isTyping, setIsTyping] = useState(false)
  const [aiSuggestions, setAiSuggestions] = useState<string[]>([])
  const fileInputRef = useRef<HTMLInputElement>(null)
  const chatEndRef = useRef<HTMLDivElement>(null)
  
  const [newTicket, setNewTicket] = useState({
    subject: '',
    description: '',
    category: 'general' as SupportTicket['category'],
    priority: 'medium' as SupportTicket['priority'],
    errorCode: '',
    errorStack: '',
    enableChat: false
  })

  // AI responses for common issues
  const aiResponses: Record<string, string> = {
    'meta': '🤖 **AI Assistant**: Para problemas con Meta API, te sugiero:\n1. Ve a Integraciones → Meta\n2. Haz clic en "Reconectar"\n3. Autoriza nuevamente la aplicación\n\n¿Esto resuelve tu problema?',
    'factura': '🤖 **AI Assistant**: Para temas de facturación:\n1. Ve a Billing → Facturas\n2. Descarga la factura deseada\n3. Si necesitas datos fiscales, contacta a tu ejecutivo\n\n¿Necesitas más ayuda?',
    'lento': '🤖 **AI Assistant**: Para problemas de rendimiento:\n1. Limpia el caché del navegador\n2. Verifica tu conexión a internet\n3. Intenta en modo incógnito\n\n¿El problema persiste?',
    'error': '🤖 **AI Assistant**: He detectado un error. Por favor:\n1. ¿Puedes describir qué estabas haciendo?\n2. ¿El error aparece siempre o es intermitente?\n3. ¿Otros usuarios tienen el mismo problema?\n\nEstoy recopilando información para el equipo técnico.',
    'default': '🤖 **AI Assistant**: Gracias por contactarnos. Un agente de soporte revisará tu caso pronto. Mientras tanto, ¿puedo ayudarte con algo más?'
  }

  // Create auto-ticket from system errors
  const createAutoTicket = useCallback((error: ErrorEvent | PromiseRejectionEvent) => {
    const errorMessage = 'message' in error ? error.message : String(error.reason)
    const errorStack = 'error' in error && error.error ? error.error.stack : ''
    
    const now = new Date()
    const autoTicket: SupportTicket = {
      id: `auto_${Date.now()}`,
      ticketNumber: `TKT-AUTO-${Date.now().toString().slice(-6)}`,
      subject: `🚨 [AUTO] Error detectado: ${errorMessage.slice(0, 50)}...`,
      description: `Error automáticamente detectado por el sistema.\n\nMensaje: ${errorMessage}`,
      category: 'auto_error',
      priority: 'high',
      status: 'open',
      createdAt: now,
      updatedAt: now,
      daysOpen: 0,
      slaDeadline: new Date(now.getTime() + 24 * 60 * 60 * 1000),
      slaBreach: false,
      messages: [
        {
          id: `msg_auto_${Date.now()}`,
          sender: 'system',
          senderName: 'Sistema Automático',
          content: `🚨 **Error Detectado Automáticamente**\n\n**Mensaje:** ${errorMessage}\n\n**Stack:**\n\`\`\`\n${errorStack || 'No disponible'}\n\`\`\``,
          timestamp: now
        }
      ],
      attachments: [],
      systemInfo: {
        browser: navigator.userAgent.match(/Chrome\/[\d.]+|Firefox\/[\d.]+|Safari\/[\d.]+/)?.[0] || 'Unknown',
        os: navigator.platform,
        screenResolution: `${window.screen.width}x${window.screen.height}`,
        url: window.location.pathname,
        timestamp: now,
        userAgent: navigator.userAgent
      },
      errorCode: errorMessage.split(':')[0] || 'UNKNOWN_ERROR',
      errorStack: errorStack || undefined,
      chatEnabled: false,
      chatActive: false,
      isAutoGenerated: true
    }

    setTickets(prev => [autoTicket, ...prev])
    
    // Notify user
    
  }, [])

  useEffect(() => {
    loadData()
    setupAutoErrorHandler(createAutoTicket)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  useEffect(() => {
    if (chatEndRef.current && selectedTicket?.chatActive) {
      chatEndRef.current.scrollIntoView({ behavior: 'smooth' })
    }
  }, [selectedTicket?.messages, selectedTicket?.chatActive])

  const loadData = async () => {
    setIsLoading(true)
    await new Promise(resolve => setTimeout(resolve, 500))

    const now = new Date()
    
    setTickets([
      {
        id: 'ticket_001',
        ticketNumber: 'TKT-2025-001234',
        subject: 'Error crítico al conectar con Meta API',
        description: 'Al intentar sincronizar campañas, aparece un error de autenticación',
        category: 'error',
        priority: 'critical',
        status: 'in_progress',
        createdAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000),
        updatedAt: new Date(now.getTime() - 4 * 60 * 60 * 1000),
        daysOpen: 5,
        slaDeadline: new Date(now.getTime() + 1 * 24 * 60 * 60 * 1000),
        slaBreach: false,
        assignedTo: 'Carlos Soporte',
        chatEnabled: true,
        chatActive: true,
        agentOnline: true,
        messages: [
          { id: 'msg_001', sender: 'client', senderName: 'María González', content: 'Al intentar sincronizar campañas, aparece error de autenticación', timestamp: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000) },
          { id: 'msg_ai', sender: 'ai', senderName: 'AI Assistant', content: aiResponses['meta'], timestamp: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000 + 30000) },
          { id: 'msg_002', sender: 'support', senderName: 'Carlos Soporte', content: '¿Podrías reconectar tu cuenta de Meta?', timestamp: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000) },
          { id: 'msg_003', sender: 'client', senderName: 'María González', content: 'Ya lo intenté pero sigue el mismo error', timestamp: new Date(now.getTime() - 12 * 60 * 60 * 1000) }
        ],
        attachments: [
          { id: 'att_001', name: 'error_screenshot.png', type: 'screenshot', url: '#', size: '245 KB', uploadedAt: new Date() }
        ],
        systemInfo: {
          browser: 'Chrome 120.0.6099.129',
          os: 'Windows 11',
          screenResolution: '1920x1080',
          url: '/dashboard/campaigns',
          timestamp: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000),
          userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'
        },
        errorCode: 'META_AUTH_TOKEN_EXPIRED'
      },
      {
        id: 'ticket_002',
        ticketNumber: 'TKT-2025-001189',
        subject: 'Bug: Reportes muestran datos duplicados',
        description: 'Al generar el reporte semanal, algunos datos aparecen duplicados',
        category: 'bug',
        priority: 'high',
        status: 'open',
        createdAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000),
        updatedAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000),
        daysOpen: 2,
        slaDeadline: new Date(now.getTime() + 2 * 24 * 60 * 60 * 1000),
        slaBreach: false,
        messages: [],
        attachments: [],
        chatEnabled: false,
        chatActive: false
      }
    ])

    setFaqs([
      { id: 'faq_001', question: '¿Cómo conecto mi cuenta de Meta?', answer: 'Ve a Integraciones > Meta > Conectar.', category: 'Integraciones', views: 245 },
      { id: 'faq_002', question: '¿Cómo cambio mi plan?', answer: 'En Billing > Upgrade puedes ver los planes.', category: 'Facturación', views: 189 },
      { id: 'faq_003', question: '¿Cómo reporto un bug?', answer: 'Usa el botón "Nuevo Ticket" y selecciona categoría "Bug".', category: 'Soporte', views: 156 }
    ])

    setIsLoading(false)
  }

  const generateTicketNumber = () => {
    const year = new Date().getFullYear()
    const num = Math.floor(Math.random() * 900000) + 100000
    return `TKT-${year}-${num}`
  }

  const getSystemInfo = (): SystemInfo => {
    return {
      browser: navigator.userAgent.match(/Chrome\/[\d.]+|Firefox\/[\d.]+|Safari\/[\d.]+/)?.[0] || 'Unknown',
      os: navigator.platform,
      screenResolution: `${window.screen.width}x${window.screen.height}`,
      url: window.location.pathname,
      timestamp: new Date(),
      userAgent: navigator.userAgent
    }
  }

  const captureScreenshot = async () => {
    const screenshot: Attachment = {
      id: `att_${Date.now()}`,
      name: `screenshot_${new Date().toISOString().split('T')[0]}.png`,
      type: 'screenshot',
      url: '#',
      size: `${Math.floor(Math.random() * 500) + 100} KB`,
      uploadedAt: new Date()
    }
    setPendingAttachments(prev => [...prev, screenshot])
  }

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files
    if (!files) return

    Array.from(files).forEach(file => {
      const attachment: Attachment = {
        id: `att_${Date.now()}_${Math.random()}`,
        name: file.name,
        type: file.type.startsWith('image') ? 'image' : 'document',
        url: URL.createObjectURL(file),
        size: `${(file.size / 1024).toFixed(1)} KB`,
        uploadedAt: new Date()
      }
      setPendingAttachments(prev => [...prev, attachment])
    })
  }

  const removeAttachment = (id: string) => {
    setPendingAttachments(prev => prev.filter(a => a.id !== id))
  }

  const getAIResponse = (text: string): string => {
    const lowerText = text.toLowerCase()
    if (lowerText.includes('meta') || lowerText.includes('facebook')) return aiResponses['meta']
    if (lowerText.includes('factura') || lowerText.includes('pago') || lowerText.includes('cobro')) return aiResponses['factura']
    if (lowerText.includes('lento') || lowerText.includes('carga') || lowerText.includes('demora')) return aiResponses['lento']
    if (lowerText.includes('error') || lowerText.includes('falla') || lowerText.includes('bug')) return aiResponses['error']
    return aiResponses['default']
  }

  const generateAISuggestions = (text: string) => {
    const suggestions: string[] = []
    const lowerText = text.toLowerCase()
    
    if (lowerText.includes('meta') || lowerText.includes('api')) {
      suggestions.push('¿Has intentado reconectar la cuenta?')
      suggestions.push('¿El error aparece en todas las campañas?')
    }
    if (lowerText.includes('error') || lowerText.includes('bug')) {
      suggestions.push('¿Puedes adjuntar una captura de pantalla?')
      suggestions.push('¿Cuándo empezó a ocurrir el problema?')
    }
    if (lowerText.includes('factura') || lowerText.includes('pago')) {
      suggestions.push('¿Necesitas factura de qué período?')
      suggestions.push('¿Cambió tu información fiscal?')
    }
    
    setAiSuggestions(suggestions)
  }

  const createTicket = () => {
    if (!newTicket.subject.trim() || !newTicket.description.trim()) {
      alert('Por favor completa el asunto y la descripción')
      return
    }
    
    const now = new Date()
    const slaHours = newTicket.priority === 'critical' ? 4 : newTicket.priority === 'high' ? 24 : newTicket.priority === 'medium' ? 48 : 72
    
    const initialMessages: TicketMessage[] = [
      { 
        id: `msg_${Date.now()}`, 
        sender: 'client', 
        senderName: 'Admin', 
        content: newTicket.description, 
        timestamp: now,
        attachments: pendingAttachments.length > 0 ? [...pendingAttachments] : undefined
      }
    ]

    // Add AI response if applicable
    const aiResponse = getAIResponse(newTicket.description)
    initialMessages.push({
      id: `msg_ai_${Date.now()}`,
      sender: 'ai',
      senderName: 'AI Assistant',
      content: aiResponse,
      timestamp: new Date(now.getTime() + 2000)
    })
    
    const ticket: SupportTicket = {
      id: `ticket_${Date.now()}`,
      ticketNumber: generateTicketNumber(),
      subject: newTicket.subject,
      description: newTicket.description,
      category: newTicket.category,
      priority: newTicket.priority,
      status: 'open',
      createdAt: now,
      updatedAt: now,
      daysOpen: 0,
      slaDeadline: new Date(now.getTime() + slaHours * 60 * 60 * 1000),
      slaBreach: false,
      messages: initialMessages,
      attachments: [...pendingAttachments],
      systemInfo: getSystemInfo(),
      errorCode: newTicket.errorCode || undefined,
      errorStack: newTicket.errorStack || undefined,
      chatEnabled: newTicket.enableChat,
      chatActive: newTicket.enableChat,
      agentOnline: false
    }
    
    setTickets(prev => [ticket, ...prev])
    setNewTicket({ subject: '', description: '', category: 'general', priority: 'medium', errorCode: '', errorStack: '', enableChat: false })
    setPendingAttachments([])
    setShowNewTicket(false)
    setSelectedTicket(ticket)
  }

  const sendMessage = () => {
    if (!newMessage.trim() || !selectedTicket) return
    
    const message: TicketMessage = {
      id: `msg_${Date.now()}`,
      sender: 'client',
      senderName: 'Admin',
      content: newMessage,
      timestamp: new Date(),
      attachments: pendingAttachments.length > 0 ? [...pendingAttachments] : undefined
    }
    
    const updatedMessages = [...selectedTicket.messages, message]
    
    setTickets(prev => prev.map(t => 
      t.id === selectedTicket.id ? { 
        ...t, 
        messages: updatedMessages,
        attachments: [...t.attachments, ...pendingAttachments],
        updatedAt: new Date(),
        status: 'waiting_response' as const
      } : t
    ))
    
    setSelectedTicket(prev => prev ? { 
      ...prev, 
      messages: updatedMessages,
      attachments: [...prev.attachments, ...pendingAttachments]
    } : null)
    
    const messageCopy = newMessage
    setNewMessage('')
    setPendingAttachments([])
    setAiSuggestions([])

    // Simulate AI response in chat mode
    if (selectedTicket.chatActive && !selectedTicket.agentOnline) {
      setIsTyping(true)
      setTimeout(() => {
        const aiMessage: TicketMessage = {
          id: `msg_ai_${Date.now()}`,
          sender: 'ai',
          senderName: 'AI Assistant',
          content: getAIResponse(messageCopy),
          timestamp: new Date()
        }
        
        setTickets(prev => prev.map(t => 
          t.id === selectedTicket.id ? { 
            ...t, 
            messages: [...t.messages, message, aiMessage]
          } : t
        ))
        
        setSelectedTicket(prev => prev ? { 
          ...prev, 
          messages: [...prev.messages, aiMessage]
        } : null)
        
        setIsTyping(false)
      }, 1500)
    }
  }

  const toggleChat = (ticketId: string) => {
    setTickets(prev => prev.map(t => 
      t.id === ticketId ? { ...t, chatActive: !t.chatActive } : t
    ))
    if (selectedTicket?.id === ticketId) {
      setSelectedTicket(prev => prev ? { ...prev, chatActive: !prev.chatActive } : null)
    }
  }

  const requestLiveAgent = () => {
    if (!selectedTicket) return
    
    const systemMessage: TicketMessage = {
      id: `msg_sys_${Date.now()}`,
      sender: 'system',
      senderName: 'Sistema',
      content: '📞 **Solicitando agente en vivo...** Un representante de soporte se conectará en breve.',
      timestamp: new Date()
    }
    
    setTickets(prev => prev.map(t => 
      t.id === selectedTicket.id ? { ...t, messages: [...t.messages, systemMessage] } : t
    ))
    
    setSelectedTicket(prev => prev ? { ...prev, messages: [...prev.messages, systemMessage] } : null)

    // Simulate agent connecting
    setTimeout(() => {
      const agentMessage: TicketMessage = {
        id: `msg_agent_${Date.now()}`,
        sender: 'support',
        senderName: 'Carlos Soporte',
        content: '¡Hola! Soy Carlos del equipo de soporte. He revisado tu caso y estoy aquí para ayudarte. ¿Puedes darme más detalles sobre el error?',
        timestamp: new Date()
      }
      
      setTickets(prev => prev.map(t => 
        t.id === selectedTicket.id ? { 
          ...t, 
          messages: [...t.messages, agentMessage],
          agentOnline: true,
          assignedTo: 'Carlos Soporte'
        } : t
      ))
      
      setSelectedTicket(prev => prev ? { 
        ...prev, 
        messages: [...prev.messages, agentMessage],
        agentOnline: true,
        assignedTo: 'Carlos Soporte'
      } : null)
    }, 3000)
  }

  const closeTicket = (ticketId: string) => {
    if (!confirm('¿Cerrar este ticket?')) return
    
    setTickets(prev => prev.map(t => 
      t.id === ticketId ? { ...t, status: 'closed' as const, closedAt: new Date(), chatActive: false } : t
    ))
    
    if (selectedTicket?.id === ticketId) {
      setSelectedTicket(prev => prev ? { ...prev, status: 'closed', closedAt: new Date(), chatActive: false } : null)
    }
  }

  const reopenTicket = (ticketId: string) => {
    setTickets(prev => prev.map(t => 
      t.id === ticketId ? { ...t, status: 'open' as const, closedAt: undefined } : t
    ))
    
    if (selectedTicket?.id === ticketId) {
      setSelectedTicket(prev => prev ? { ...prev, status: 'open', closedAt: undefined } : null)
    }
  }

  const getStatusStyle = (status: string) => {
    switch (status) {
      case 'open': return 'bg-blue-500/20 text-blue-400'
      case 'in_progress': return 'bg-yellow-500/20 text-yellow-400'
      case 'waiting_response': return 'bg-purple-500/20 text-purple-400'
      case 'resolved': return 'bg-green-500/20 text-green-400'
      case 'closed': return 'bg-slate-500/20 text-slate-400'
      default: return 'bg-slate-500/20 text-slate-400'
    }
  }

  const getPriorityStyle = (priority: string) => {
    switch (priority) {
      case 'critical': return 'bg-red-500/20 text-red-400 animate-pulse'
      case 'high': return 'bg-orange-500/20 text-orange-400'
      case 'medium': return 'bg-yellow-500/20 text-yellow-400'
      case 'low': return 'bg-green-500/20 text-green-400'
      default: return 'bg-slate-500/20 text-slate-400'
    }
  }

  const getCategoryIcon = (category: string) => {
    switch (category) {
      case 'bug': return <Bug className="w-4 h-4" />
      case 'error': return <AlertTriangle className="w-4 h-4" />
      case 'auto_error': return <AlertCircle className="w-4 h-4" />
      case 'billing': return <CreditCard className="w-4 h-4" />
      case 'feature': return <Zap className="w-4 h-4" />
      case 'performance': return <Cpu className="w-4 h-4" />
      case 'security': return <Settings className="w-4 h-4" />
      default: return <HelpCircle className="w-4 h-4" />
    }
  }

  const getSenderStyle = (sender: string) => {
    switch (sender) {
      case 'client': return 'bg-blue-500/10 ml-8'
      case 'support': return 'bg-orange-500/10 mr-8'
      case 'ai': return 'bg-purple-500/10 mr-8 border border-purple-500/30'
      case 'system': return 'bg-slate-500/10 mx-4 text-center'
      default: return 'bg-slate-500/10'
    }
  }

  const getSenderIcon = (sender: string) => {
    switch (sender) {
      case 'ai': return <Bot className="w-4 h-4 text-purple-400" />
      case 'system': return <AlertCircle className="w-4 h-4 text-slate-400" />
      case 'support': return <HelpCircle className="w-4 h-4 text-orange-400" />
      default: return null
    }
  }

  const getDaysOpenWarning = (days: number, status: string) => {
    if (status === 'closed' || status === 'resolved') return null
    if (days >= 7) return { text: `⚠️ ${days} días`, style: 'text-red-400' }
    if (days >= 3) return { text: `${days} días`, style: 'text-yellow-400' }
    return { text: `${days}d`, style: 'text-slate-400' }
  }

  const filteredTickets = tickets.filter(t => {
    if (filter === 'open') return t.status === 'open' || t.status === 'in_progress' || t.status === 'waiting_response'
    if (filter === 'resolved') return t.status === 'resolved'
    if (filter === 'closed') return t.status === 'closed'
    return true
  })

  const openCount = tickets.filter(t => t.status !== 'resolved' && t.status !== 'closed').length
  const autoTicketCount = tickets.filter(t => t.isAutoGenerated).length

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-center">
          <div className="w-12 h-12 border-4 border-orange-500/30 border-t-orange-500 rounded-full animate-spin mx-auto mb-4" />
          <p className="text-slate-400">Cargando Support Center...</p>
        </div>
      </div>
    )
  }

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="flex items-center justify-between">
        <h3 className="text-lg font-bold text-white flex items-center gap-2">
          <HelpCircle className="w-5 h-5 text-orange-400" />
          Support Center
          <span className="text-xs px-2 py-0.5 bg-purple-500/20 text-purple-400 rounded flex items-center gap-1">
            <Bot className="w-3 h-3" /> AI Powered
          </span>
        </h3>
        <div className="flex items-center gap-2">
          <NeuromorphicButton variant="secondary" size="sm" onClick={loadData}>
            <RefreshCw className="w-4 h-4 mr-1" />
            Refresh
          </NeuromorphicButton>
          <NeuromorphicButton variant="primary" size="sm" onClick={() => setShowNewTicket(true)}>
            <Plus className="w-4 h-4 mr-1" />
            Nuevo Ticket
          </NeuromorphicButton>
        </div>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-5 gap-3">
        <div className="p-3 bg-slate-800/50 rounded-lg text-center">
          <p className="text-2xl font-bold text-white">{tickets.length}</p>
          <p className="text-xs text-slate-400">Total</p>
        </div>
        <div className="p-3 bg-blue-500/10 rounded-lg text-center cursor-pointer" onClick={() => setFilter('open')}>
          <p className="text-2xl font-bold text-blue-400">{openCount}</p>
          <p className="text-xs text-slate-400">Abiertos</p>
        </div>
        <div className="p-3 bg-green-500/10 rounded-lg text-center cursor-pointer" onClick={() => setFilter('resolved')}>
          <p className="text-2xl font-bold text-green-400">{tickets.filter(t => t.status === 'resolved').length}</p>
          <p className="text-xs text-slate-400">Resueltos</p>
        </div>
        <div className="p-3 bg-purple-500/10 rounded-lg text-center">
          <p className="text-2xl font-bold text-purple-400">{tickets.filter(t => t.chatActive).length}</p>
          <p className="text-xs text-slate-400">Chat Activo</p>
        </div>
        <div className="p-3 bg-red-500/10 rounded-lg text-center">
          <p className="text-2xl font-bold text-red-400">{autoTicketCount}</p>
          <p className="text-xs text-slate-400">Auto-Tickets</p>
        </div>
      </div>

      {/* New Ticket Form */}
      {showNewTicket && (
        <NeuromorphicCard variant="glow" className="p-4">
          <div className="flex items-center justify-between mb-4">
            <h4 className="text-white font-medium flex items-center gap-2">
              <Plus className="w-4 h-4" />
              Crear Nuevo Ticket
            </h4>
            <button onClick={() => setShowNewTicket(false)} className="p-1 hover:bg-slate-700 rounded" aria-label="Cerrar">
              <X className="w-4 h-4 text-slate-400" />
            </button>
          </div>
          
          <div className="space-y-4">
            <div>
              <label className="text-slate-400 text-xs block mb-1">Asunto *</label>
              <input
                type="text"
                placeholder="Describe brevemente el problema"
                value={newTicket.subject}
                onChange={(e) => setNewTicket({ ...newTicket, subject: e.target.value })}
                className="w-full px-3 py-2 bg-slate-800 border border-slate-700 rounded text-white"
              />
            </div>

            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="text-slate-400 text-xs block mb-1">Categoría</label>
                <select
                  value={newTicket.category}
                  onChange={(e) => setNewTicket({ ...newTicket, category: e.target.value as SupportTicket['category'] })}
                  className="w-full px-3 py-2 bg-slate-800 border border-slate-700 rounded text-white"
                >
                  <option value="general">General</option>
                  <option value="bug">🐛 Bug</option>
                  <option value="error">⚠️ Error del Sistema</option>
                  <option value="billing">💳 Facturación</option>
                  <option value="feature">⚡ Nueva Funcionalidad</option>
                  <option value="performance">🚀 Rendimiento</option>
                  <option value="security">🔒 Seguridad</option>
                </select>
              </div>
              <div>
                <label className="text-slate-400 text-xs block mb-1">Prioridad</label>
                <select
                  value={newTicket.priority}
                  onChange={(e) => setNewTicket({ ...newTicket, priority: e.target.value as SupportTicket['priority'] })}
                  className="w-full px-3 py-2 bg-slate-800 border border-slate-700 rounded text-white"
                >
                  <option value="low">🟢 Baja (72h)</option>
                  <option value="medium">🟡 Media (48h)</option>
                  <option value="high">🟠 Alta (24h)</option>
                  <option value="critical">🔴 Crítica (4h)</option>
                </select>
              </div>
            </div>

            <div>
              <label className="text-slate-400 text-xs block mb-1">Descripción *</label>
              <textarea
                placeholder="Describe el problema en detalle..."
                value={newTicket.description}
                onChange={(e) => {
                  setNewTicket({ ...newTicket, description: e.target.value })
                  generateAISuggestions(e.target.value)
                }}
                className="w-full px-3 py-2 bg-slate-800 border border-slate-700 rounded text-white h-24 resize-none"
              />
            </div>

            {/* AI Suggestions */}
            {aiSuggestions.length > 0 && (
              <div className="p-3 bg-purple-500/10 rounded-lg border border-purple-500/30">
                <p className="text-purple-400 text-xs flex items-center gap-1 mb-2">
                  <Sparkles className="w-3 h-3" /> Sugerencias de IA
                </p>
                <div className="flex flex-wrap gap-2">
                  {aiSuggestions.map((s, i) => (
                    <button
                      key={s}
                      onClick={() => setNewTicket({ ...newTicket, description: newTicket.description + '\n\n' + s })}
                      className="text-xs px-2 py-1 bg-purple-500/20 text-purple-300 rounded hover:bg-purple-500/30"
                    >
                      {s}
                    </button>
                  ))}
                </div>
              </div>
            )}

            {/* Chat Option */}
            <div className="p-3 bg-slate-800/50 rounded-lg border border-slate-700">
              <label className="flex items-center justify-between cursor-pointer">
                <div className="flex items-center gap-2">
                  <MessageCircle className="w-4 h-4 text-green-400" />
                  <span className="text-white text-sm">Habilitar Chat en Tiempo Real</span>
                </div>
                <div 
                  className={`w-12 h-6 rounded-full relative transition-colors ${newTicket.enableChat ? 'bg-green-500' : 'bg-slate-600'}`}
                  onClick={() => setNewTicket({ ...newTicket, enableChat: !newTicket.enableChat })}
                >
                  <div className={`absolute w-5 h-5 bg-white rounded-full top-0.5 transition-transform ${newTicket.enableChat ? 'left-6' : 'left-0.5'}`} />
                </div>
              </label>
              <p className="text-xs text-slate-500 mt-1">
                {newTicket.enableChat 
                  ? '💬 Podrás chatear directamente con soporte cuando se conecte un agente' 
                  : '📧 Modo email: envía mensajes y recibe respuestas en el historial'}
              </p>
            </div>

            {/* Attachments */}
            <div>
              <label className="text-slate-400 text-xs block mb-1">Adjuntos</label>
              <div className="flex gap-2 mb-2">
                <input
                  type="file"
                  ref={fileInputRef}
                  onChange={handleFileUpload}
                  multiple
                  className="hidden"
                />
                <NeuromorphicButton variant="secondary" size="sm" onClick={() => fileInputRef.current?.click()}>
                  <Paperclip className="w-4 h-4 mr-1" />
                  Adjuntar
                </NeuromorphicButton>
                <NeuromorphicButton variant="secondary" size="sm" onClick={captureScreenshot}>
                  <Camera className="w-4 h-4 mr-1" />
                  Captura
                </NeuromorphicButton>
              </div>
              {pendingAttachments.length > 0 && (
                <div className="flex flex-wrap gap-2">
                  {pendingAttachments.map(att => (
                    <div key={att.id} className="flex items-center gap-2 px-2 py-1 bg-slate-800 rounded text-xs">
                      <span className="text-white">{att.name}</span>
                      <button onClick={() => removeAttachment(att.id)} aria-label="Eliminar adjunto">
                        <X className="w-3 h-3 text-red-400" />
                      </button>
                    </div>
                  ))}
                </div>
              )}
            </div>

            <div className="flex justify-end gap-2">
              <NeuromorphicButton variant="secondary" size="sm" onClick={() => setShowNewTicket(false)}>
                Cancelar
              </NeuromorphicButton>
              <NeuromorphicButton variant="primary" size="sm" onClick={createTicket}>
                <Send className="w-4 h-4 mr-1" />
                Crear Ticket
              </NeuromorphicButton>
            </div>
          </div>
        </NeuromorphicCard>
      )}

      {/* Filter Tabs */}
      <div className="flex gap-2">
        {(['all', 'open', 'resolved', 'closed'] as const).map(f => (
          <button
            key={f}
            onClick={() => setFilter(f)}
            className={`px-3 py-1 text-sm rounded capitalize ${filter === f ? 'bg-orange-500 text-white' : 'bg-slate-800 text-slate-400'}`}
          >
            {f === 'all' ? 'Todos' : f === 'open' ? 'Abiertos' : f === 'resolved' ? 'Resueltos' : 'Cerrados'}
          </button>
        ))}
      </div>

      <div className="grid grid-cols-2 gap-4">
        {/* Tickets List */}
        <NeuromorphicCard variant="embossed" className="p-4 max-h-[500px] overflow-y-auto">
          <h4 className="text-white font-medium mb-3">Mis Tickets ({filteredTickets.length})</h4>
          <div className="space-y-2">
            {filteredTickets.map(ticket => {
              const daysWarning = getDaysOpenWarning(ticket.daysOpen, ticket.status)
              return (
                <div 
                  key={ticket.id}
                  onClick={() => setSelectedTicket(ticket)}
                  className={`p-3 rounded-lg cursor-pointer transition-colors ${
                    selectedTicket?.id === ticket.id 
                      ? 'bg-slate-800 border border-orange-500/50' 
                      : 'bg-slate-800/50 hover:bg-slate-800'
                  }`}
                >
                  <div className="flex items-center justify-between mb-2">
                    <div className="flex items-center gap-2">
                      <span className={`p-1 rounded ${getPriorityStyle(ticket.priority)}`}>
                        {getCategoryIcon(ticket.category)}
                      </span>
                      <span className={`text-xs px-2 py-0.5 rounded ${getStatusStyle(ticket.status)}`}>
                        {ticket.status.replace('_', ' ')}
                      </span>
                      {ticket.chatActive && (
                        <span className="text-xs px-1 py-0.5 bg-green-500/20 text-green-400 rounded flex items-center gap-1">
                          <Circle className="w-2 h-2 fill-green-400" />
                          Chat
                        </span>
                      )}
                      {ticket.isAutoGenerated && (
                        <span className="text-xs px-1 py-0.5 bg-red-500/20 text-red-400 rounded">
                          AUTO
                        </span>
                      )}
                    </div>
                    <span className="text-xs text-orange-400 font-mono">{ticket.ticketNumber}</span>
                  </div>
                  <p className="text-white text-sm font-medium mb-1 line-clamp-1">{ticket.subject}</p>
                  <div className="flex items-center justify-between text-xs">
                    <span className="text-slate-500">{ticket.createdAt.toLocaleDateString()}</span>
                    {daysWarning && <span className={daysWarning.style}>{daysWarning.text}</span>}
                  </div>
                </div>
              )
            })}
          </div>
        </NeuromorphicCard>

        {/* Ticket Detail / Chat */}
        <NeuromorphicCard variant="embossed" className="p-4 max-h-[500px] flex flex-col">
          {selectedTicket ? (
            <>
              {/* Ticket Header */}
              <div className="border-b border-slate-700 pb-3 mb-3">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-sm font-mono text-orange-400">{selectedTicket.ticketNumber}</span>
                  <div className="flex items-center gap-2">
                    {selectedTicket.chatEnabled && (
                      <button
                        onClick={() => toggleChat(selectedTicket.id)}
                        className={`flex items-center gap-1 px-2 py-1 rounded text-xs ${
                          selectedTicket.chatActive ? 'bg-green-500/20 text-green-400' : 'bg-slate-700 text-slate-400'
                        }`}
                      >
                        {selectedTicket.chatActive ? <Wifi className="w-3 h-3" /> : <WifiOff className="w-3 h-3" />}
                        {selectedTicket.chatActive ? 'Chat ON' : 'Chat OFF'}
                      </button>
                    )}
                    <span className={`text-xs px-2 py-0.5 rounded ${getStatusStyle(selectedTicket.status)}`}>
                      {selectedTicket.status}
                    </span>
                  </div>
                </div>
                <h4 className="text-white font-medium mb-2">{selectedTicket.subject}</h4>
                <div className="flex items-center gap-3 text-xs text-slate-400">
                  <span><Calendar className="w-3 h-3 inline mr-1" />{selectedTicket.createdAt.toLocaleDateString()}</span>
                  <span><Clock className="w-3 h-3 inline mr-1" />{selectedTicket.daysOpen}d</span>
                  {selectedTicket.assignedTo && (
                    <span className="text-blue-400">👤 {selectedTicket.assignedTo}</span>
                  )}
                  {selectedTicket.agentOnline && (
                    <span className="text-green-400 flex items-center gap-1">
                      <Circle className="w-2 h-2 fill-green-400" /> En línea
                    </span>
                  )}
                </div>
              </div>

              {/* Messages */}
              <div className="flex-1 overflow-y-auto space-y-3 mb-3">
                {selectedTicket.messages.map(msg => (
                  <div key={msg.id} className={`p-3 rounded-lg ${getSenderStyle(msg.sender)}`}>
                    <div className="flex items-center justify-between mb-1">
                      <span className={`text-xs font-medium flex items-center gap-1 ${
                        msg.sender === 'ai' ? 'text-purple-400' :
                        msg.sender === 'support' ? 'text-orange-400' :
                        msg.sender === 'system' ? 'text-slate-400' :
                        'text-blue-400'
                      }`}>
                        {getSenderIcon(msg.sender)}
                        {msg.senderName}
                      </span>
                      <span className="text-xs text-slate-500">{msg.timestamp.toLocaleTimeString()}</span>
                    </div>
                    <div className="text-white text-sm whitespace-pre-wrap">{msg.content}</div>
                    {msg.attachments && msg.attachments.length > 0 && (
                      <div className="flex gap-1 mt-2">
                        {msg.attachments.map(att => (
                          <span key={att.id} className="text-xs text-slate-400 flex items-center gap-1">
                            <Paperclip className="w-3 h-3" />{att.name}
                          </span>
                        ))}
                      </div>
                    )}
                  </div>
                ))}
                
                {isTyping && (
                  <div className="p-3 rounded-lg bg-purple-500/10 mr-8">
                    <span className="text-purple-400 text-xs flex items-center gap-2">
                      <Bot className="w-4 h-4" />
                      AI Assistant está escribiendo...
                      <span className="animate-pulse">●●●</span>
                    </span>
                  </div>
                )}
                <div ref={chatEndRef} />
              </div>

              {/* Actions */}
              <div className="flex gap-2 mb-3">
                {selectedTicket.chatActive && !selectedTicket.agentOnline && (
                  <NeuromorphicButton variant="secondary" size="sm" onClick={requestLiveAgent}>
                    <Phone className="w-4 h-4 mr-1" />
                    Solicitar Agente
                  </NeuromorphicButton>
                )}
                {selectedTicket.status !== 'closed' && (
                  <NeuromorphicButton variant="secondary" size="sm" onClick={() => closeTicket(selectedTicket.id)}>
                    <XCircle className="w-4 h-4 mr-1" />
                    Cerrar
                  </NeuromorphicButton>
                )}
                {selectedTicket.status === 'closed' && (
                  <NeuromorphicButton variant="secondary" size="sm" onClick={() => reopenTicket(selectedTicket.id)}>
                    <RotateCcw className="w-4 h-4 mr-1" />
                    Reabrir
                  </NeuromorphicButton>
                )}
              </div>

              {/* Reply Input */}
              {selectedTicket.status !== 'closed' && (
                <div className="space-y-2 pt-2 border-t border-slate-700">
                  <div className="flex gap-2">
                    <input
                      type="text"
                      placeholder={selectedTicket.chatActive ? "Escribe tu mensaje..." : "Escribe tu respuesta..."}
                      value={newMessage}
                      onChange={(e) => setNewMessage(e.target.value)}
                      onKeyPress={(e) => e.key === 'Enter' && sendMessage()}
                      className="flex-1 px-3 py-2 bg-slate-800 border border-slate-700 rounded text-white"
                    />
                    <button onClick={() => fileInputRef.current?.click()} className="p-2 hover:bg-slate-700 rounded" aria-label="Adjuntar archivo">
                      <Paperclip className="w-4 h-4 text-slate-400" />
                    </button>
                    <NeuromorphicButton variant="primary" size="sm" onClick={sendMessage}>
                      <Send className="w-4 h-4" />
                    </NeuromorphicButton>
                  </div>
                  {pendingAttachments.length > 0 && (
                    <div className="flex flex-wrap gap-2">
                      {pendingAttachments.map(att => (
                        <div key={att.id} className="flex items-center gap-2 px-2 py-1 bg-slate-800 rounded text-xs">
                          <span className="text-white">{att.name}</span>
                          <button onClick={() => removeAttachment(att.id)} aria-label="Eliminar adjunto">
                            <X className="w-3 h-3 text-red-400" />
                          </button>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              )}
            </>
          ) : (
            <div className="flex-1 flex flex-col items-center justify-center text-slate-400">
              <MessageSquare className="w-12 h-12 mb-2" />
              <p>Selecciona un ticket</p>
            </div>
          )}
        </NeuromorphicCard>
      </div>

      {/* FAQ Section */}
      <NeuromorphicCard variant="embossed" className="p-4">
        <h4 className="text-white font-medium mb-3 flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-purple-400" />
          Preguntas Frecuentes
        </h4>
        <div className="grid grid-cols-3 gap-2">
          {faqs.map(faq => (
            <div key={faq.id} className="p-3 bg-slate-800/50 rounded-lg hover:bg-slate-800 cursor-pointer">
              <span className="text-white text-sm">{faq.question}</span>
            </div>
          ))}
        </div>
      </NeuromorphicCard>
    </div>
  )
}

export default SupportTickets
