#!/usr/bin/env node
/**
 * Silexar Pulse - Git Hooks Installer
 * 
 * Este script instala y configura los git hooks de seguridad
 * Se ejecuta automáticamente via npm prepare
 * 
 * Uso: node scripts/install-hooks.js
 */

import { readFileSync, writeFileSync, chmodSync, existsSync, mkdirSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, resolve, join } from 'path';
import { execSync } from 'child_process';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT_DIR = resolve(__dirname, '..');

// Colores para terminal
const colors = {
  reset: '\x1b[0m',
  bright: '\x1b[1m',
  red: '\x1b[31m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  cyan: '\x1b[36m'
};

const icons = {
  check: '✅',
  cross: '❌',
  warning: '⚠️',
  info: 'ℹ️',
  gear: '⚙️',
  lock: '🔒'
};

function log(message) {
  console.log(message);
}

function success(message) {
  console.log(`${colors.green}${icons.check} ${message}${colors.reset}`);
}

function error(message) {
  console.error(`${colors.red}${icons.cross} ${message}${colors.reset}`);
}

function warning(message) {
  console.warn(`${colors.yellow}${icons.warning} ${message}${colors.reset}`);
}

function info(message) {
  console.log(`${colors.blue}${icons.info} ${message}${colors.reset}`);
}

function section(title) {
  console.log('');
  console.log(`${colors.cyan}${colors.bright}${icons.gear} ${title}${colors.reset}`);
  console.log(`${colors.cyan}${'─'.repeat(50)}${colors.reset}`);
}

/**
 * Verifica si estamos en un repositorio git
 */
function isGitRepository() {
  try {
    execSync('git rev-parse --git-dir', { cwd: ROOT_DIR, stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

/**
 * Verifica el sistema operativo
 */
function getPlatform() {
  return process.platform;
}

/**
 * Detecta la shell disponible en Windows
 */
function detectWindowsShell() {
  // Verificar Git Bash
  try {
    execSync('where git', { stdio: 'ignore' });
    return 'git-bash';
  } catch {
    // Verificar PowerShell
    try {
      execSync('where powershell', { stdio: 'ignore' });
      return 'powershell';
    } catch {
      return 'cmd';
    }
  }
}

/**
 * Crea el directorio .husky/_ si no existe
 */
function ensureHuskyDirectory() {
  const huskyDir = join(ROOT_DIR, '.husky');
  const huskyInternalDir = join(huskyDir, '_');
  
  if (!existsSync(huskyDir)) {
    mkdirSync(huskyDir, { recursive: true });
    info(`Creado directorio: ${huskyDir}`);
  }
  
  if (!existsSync(huskyInternalDir)) {
    mkdirSync(huskyInternalDir, { recursive: true });
    info(`Creado directorio: ${huskyInternalDir}`);
  }
  
  return huskyDir;
}

/**
 * Crea el archivo husky.sh necesario para los hooks
 */
function createHuskySh(huskyDir) {
  const huskyShPath = join(huskyDir, '_', 'husky.sh');
  
  const huskyShContent = `#!/usr/bin/env sh
# Generated by Silexar Pulse Git Hooks Installer
# This file is necessary for husky hooks to work

if [ -z "\$husky_skip_init" ]; then
  debug () {
    if [ "\$HUSKY_DEBUG" = "1" ]; then
      echo "husky (debug) - \$1"
    fi
  }

  readonly hook_name=\$(basename "\$0")
  debug "starting \$hook_name..."

  if [ "\$HUSKY" = "0" ]; then
    debug "HUSKY env variable is set to 0, skipping hook"
    exit 0
  fi

  if [ -f ~/.huskyrc ]; then
    debug "sourcing ~/.huskyrc"
    . ~/.huskyrc
  fi

  readonly husky_skip_init=1
  export husky_skip_init

  sh -e "\$0" \$@
  exitCode="\$?"

  if [ \$exitCode != 0 ]; then
    echo "husky - \$hook_name hook exited with code \$exitCode (error)"
  fi

  if [ \$exitCode = 127 ]; then
    echo "husky - command not found in PATH=\$PATH"
  fi

  exit \$exitCode
fi
`;

  writeFileSync(huskyShPath, huskyShContent, 'utf8');
  
  // Hacer ejecutable en Unix
  if (getPlatform() !== 'win32') {
    chmodSync(huskyShPath, 0o755);
  }
  
  success(`Creado: ${huskyShPath}`);
}

/**
 * Verifica y configura los hooks existentes
 */
function verifyHooks(huskyDir) {
  const hooks = ['pre-commit', 'commit-msg', 'pre-push'];
  
  section('Verificando Git Hooks');
  
  for (const hook of hooks) {
    const hookPath = join(huskyDir, hook);
    
    if (existsSync(hookPath)) {
      // Verificar si es ejecutable (solo en Unix)
      if (getPlatform() !== 'win32') {
        try {
          chmodSync(hookPath, 0o755);
          success(`Hook '${hook}' verificado y configurado`);
        } catch (err) {
          warning(`No se pudo hacer ejecutable: ${hook}`);
        }
      } else {
        success(`Hook '${hook}' verificado`);
      }
    } else {
      warning(`Hook '${hook}' no encontrado`);
    }
  }
}

/**
 * Crea scripts de bypass de emergencia
 */
function createBypassScripts() {
  section('Creando scripts de bypass de emergencia');
  
  const scriptsDir = join(ROOT_DIR, 'scripts');
  
  // Script de bypass para Unix
  const bypassUnixPath = join(scriptsDir, 'git-commit-bypass.sh');
  const bypassUnixContent = `#!/bin/bash
# Silexar Pulse - Git Commit Bypass (Emergencias únicamente)
# ⚠️  ADVERTENCIA: Este script omite las verificaciones de seguridad
# ⚠️  Úsalo solo en casos de emergencia cuando sea absolutamente necesario

echo "🚨 BYPASS DE SEGURIDAD ACTIVADO 🚨"
echo ""
echo "⚠️  ADVERTENCIA: Estás a punto de hacer commit SIN verificaciones de seguridad"
echo "⚠️  Esto puede exponer secretos, código vulnerable o tests fallidos"
echo ""

read -p "¿Estás seguro? Escribe 'EMERGENCY' para continuar: " confirm

if [ "\$confirm" != "EMERGENCY" ]; then
    echo "❌ Cancelado"
    exit 1
fi

echo ""
echo "📝 Mensaje de commit:"
read -p "> " message

if [ -z "\$message" ]; then
    echo "❌ Mensaje de commit requerido"
    exit 1
fi

git commit --no-verify -m "\$message"

echo ""
echo "✅ Commit realizado con bypass de seguridad"
echo "⚠️  Recuerda revisar tus cambios manualmente"
`;

  // Script de bypass para Windows
  const bypassWinPath = join(scriptsDir, 'git-commit-bypass.ps1');
  const bypassWinContent = `# Silexar Pulse - Git Commit Bypass (Emergencias únicamente)
# ⚠️  ADVERTENCIA: Este script omite las verificaciones de seguridad
# ⚠️  Úsalo solo en casos de emergencia cuando sea absolutamente necesario

Write-Host "🚨 BYPASS DE SEGURIDAD ACTIVADO 🚨" -ForegroundColor Red
Write-Host ""
Write-Host "⚠️  ADVERTENCIA: Estás a punto de hacer commit SIN verificaciones de seguridad" -ForegroundColor Yellow
Write-Host "⚠️  Esto puede exponer secretos, código vulnerable o tests fallidos" -ForegroundColor Yellow
Write-Host ""

$confirm = Read-Host "¿Estás seguro? Escribe 'EMERGENCY' para continuar"

if ($confirm -ne "EMERGENCY") {
    Write-Host "❌ Cancelado" -ForegroundColor Red
    exit 1
}

Write-Host ""
$message = Read-Host "📝 Mensaje de commit"

if ([string]::IsNullOrWhiteSpace($message)) {
    Write-Host "❌ Mensaje de commit requerido" -ForegroundColor Red
    exit 1
}

git commit --no-verify -m "$message"

Write-Host ""
Write-Host "✅ Commit realizado con bypass de seguridad" -ForegroundColor Green
Write-Host "⚠️  Recuerda revisar tus cambios manualmente" -ForegroundColor Yellow
`;

  writeFileSync(bypassUnixPath, bypassUnixContent, 'utf8');
  writeFileSync(bypassWinPath, bypassWinContent, 'utf8');
  
  // Hacer ejecutable en Unix
  if (getPlatform() !== 'win32') {
    chmodSync(bypassUnixPath, 0o755);
  }
  
  success(`Creado: scripts/git-commit-bypass.sh`);
  success(`Creado: scripts/git-commit-bypass.ps1`);
  
  info('Para usar el bypass de emergencia:');
  info('  Unix/Mac: ./scripts/git-commit-bypass.sh');
  info('  Windows:  .\\scripts\\git-commit-bypass.ps1');
  info('  O manual: git commit --no-verify -m "mensaje"');
}

/**
 * Actualiza .gitignore para excluir archivos sensibles
 */
function updateGitignore() {
  section('Verificando .gitignore');
  
  const gitignorePath = join(ROOT_DIR, '.gitignore');
  let content = '';
  
  if (existsSync(gitignorePath)) {
    content = readFileSync(gitignorePath, 'utf8');
  }
  
  const requiredEntries = [
    '# Security - Credentials',
    '*.pem',
    '*.key',
    '*.p12',
    '*.pfx',
    '.env.local',
    '.env.production',
    '.env.development.local',
    'credentials.json',
    'serviceAccountKey.json',
    '.htpasswd',
    '.netrc',
    'id_rsa',
    'id_dsa',
    'id_ecdsa',
    'id_ed25519',
    '*.log',
    '*.dump',
    '# End Security'
  ];
  
  let updated = false;
  
  for (const entry of requiredEntries) {
    if (!content.includes(entry)) {
      content += '\n' + entry;
      updated = true;
    }
  }
  
  if (updated) {
    writeFileSync(gitignorePath, content, 'utf8');
    success('.gitignore actualizado con entradas de seguridad');
  } else {
    info('.gitignore ya contiene las entradas de seguridad necesarias');
  }
}

/**
 * Función principal
 */
async function main() {
  console.log('');
  console.log(`${colors.cyan}${colors.bright}🔒 ==========================================${colors.reset}`);
  console.log(`${colors.cyan}${colors.bright}🔒  SILEXAR PULSE GIT HOOKS INSTALLER${colors.reset}`);
  console.log(`${colors.cyan}${colors.bright}🔒 ==========================================${colors.reset}`);
  console.log('');
  
  // Verificar que estamos en un repositorio git
  if (!isGitRepository()) {
    error('No se encontró un repositorio git');
    error('Ejecuta: git init');
    process.exit(1);
  }
  
  info('Repositorio git detectado');
  info(`Plataforma: ${getPlatform()}`);
  
  // Crear estructura de directorios
  section('Configurando estructura de directorios');
  const huskyDir = ensureHuskyDirectory();
  createHuskySh(huskyDir);
  
  // Verificar hooks
  verifyHooks(huskyDir);
  
  // Crear scripts de bypass
  createBypassScripts();
  
  // Actualizar .gitignore
  updateGitignore();
  
  // Resumen final
  console.log('');
  console.log(`${colors.green}${colors.bright}✅ ==========================================${colors.reset}`);
  console.log(`${colors.green}${colors.bright}✅  INSTALACIÓN COMPLETADA${colors.reset}`);
  console.log(`${colors.green}${colors.bright}✅ ==========================================${colors.reset}`);
  console.log('');
  console.log(`${colors.bright}Hooks instalados:${colors.reset}`);
  console.log('  🔒 pre-commit  - Escanea secretos, vulnerabilidades, lint y types');
  console.log('  📝 commit-msg  - Valida formato del mensaje de commit');
  console.log('  🚀 pre-push    - Ejecuta tests, audit y build check');
  console.log('');
  console.log(`${colors.bright}Scripts de seguridad:${colors.reset}`);
  console.log('  📄 scripts/security-precommit.js    - Detector de secretos');
  console.log('  📄 scripts/security-patterns.json   - Patrones de detección');
  console.log('  📄 scripts/git-commit-bypass.sh     - Bypass Unix (emergencias)');
  console.log('  📄 scripts/git-commit-bypass.ps1    - Bypass Windows (emergencias)');
  console.log('');
  console.log(`${colors.yellow}⚠️  Nota: Los hooks se ejecutan automáticamente en cada commit/push${colors.reset}`);
  console.log(`${colors.yellow}⚠️  Bypass de emergencia: git commit --no-verify${colors.reset}`);
  console.log('');
}

// Ejecutar
main().catch(err => {
  error(`Error inesperado: ${err.message}`);
  process.exit(1);
});
